INSERT INTO Station(nom_station) VALUES ('Buttinière');
INSERT INTO Station(nom_station) VALUES ('Maire de Cenon');
INSERT INTO Station(nom_station) VALUES ('Cenon Gare');
INSERT INTO Station(nom_station) VALUES ('Jean Jaures');
INSERT INTO Station(nom_station) VALUES ('Galin');
INSERT INTO Station(nom_station) VALUES ('Thiers-Benauge');
INSERT INTO Station(nom_station) VALUES ('Jardin Botanique');
INSERT INTO Station(nom_station) VALUES ('Stalingrad');
INSERT INTO Station(nom_station) VALUES ('Porte de Bourgogne');
INSERT INTO Station(nom_station) VALUES ('Place du Palais');
INSERT INTO Station(nom_station) VALUES ('Sainte-Catherine');
INSERT INTO Station(nom_station) VALUES ('Hotel de Ville');
INSERT INTO Station(nom_station) VALUES ('Meriadeck');
INSERT INTO Station(nom_station) VALUES ('St-Bruno');
INSERT INTO Station(nom_station) VALUES ('Hotel de Police');
INSERT INTO Station(nom_station) VALUES ('Gavinies');
INSERT INTO Station(nom_station) VALUES ('Stade Chaban Delmas');
INSERT INTO Station(nom_station) VALUES ('Hopital Pellegrin');
INSERT INTO Station(nom_station) VALUES ('Saint-Augustin');
INSERT INTO Station(nom_station) VALUES ('Francois Mitterrand');
INSERT INTO Station(nom_station) VALUES ('Peychotte');
INSERT INTO Station(nom_station) VALUES ('Fontaine d''Arlac');
INSERT INTO Station(nom_station) VALUES ('Alfred de Vigny');
INSERT INTO Station(nom_station) VALUES ('Pierre Mendes France');
INSERT INTO Station(nom_station) VALUES ('Quatre Chemins');
INSERT INTO Station(nom_station) VALUES ('Lycees de Merignac');
INSERT INTO Station(nom_station) VALUES ('Merignac Centre');
INSERT INTO Station(nom_station) VALUES ('Pessac Centre');
INSERT INTO Station(nom_station) VALUES ('Camponac Mediatheque');
INSERT INTO Station(nom_station) VALUES ('Bougnard');
INSERT INTO Station(nom_station) VALUES ('Saige');
INSERT INTO Station(nom_station) VALUES ('Unitec');
INSERT INTO Station(nom_station) VALUES ('Montaigne-Montesqieu');
INSERT INTO Station(nom_station) VALUES ('Doyen Brus');
INSERT INTO Station(nom_station) VALUES ('Francois Bordes');
INSERT INTO Station(nom_station) VALUES ('Art et Metiers');
INSERT INTO Station(nom_station) VALUES ('Bethanie');
INSERT INTO Station(nom_station) VALUES ('Peixotto');
INSERT INTO Station(nom_station) VALUES ('Forum');
INSERT INTO Station(nom_station) VALUES ('Roustaing');
INSERT INTO Station(nom_station) VALUES ('Barriere Saint-Genes');
INSERT INTO Station(nom_station) VALUES ('Bergonie');
INSERT INTO Station(nom_station) VALUES ('Saint-Nicolas');
INSERT INTO Station(nom_station) VALUES ('Victoire');
INSERT INTO Station(nom_station) VALUES ('Musee d''Aquitaine');
INSERT INTO Station(nom_station) VALUES ('Gambetta');
INSERT INTO Station(nom_station) VALUES ('Grand Theatre');
INSERT INTO Station(nom_station) VALUES ('Quinconces');
INSERT INTO Station(nom_station) VALUES ('CAPC');
INSERT INTO Station(nom_station) VALUES ('Chartrons');
INSERT INTO Station(nom_station) VALUES ('Cours du Medoc');
INSERT INTO Station(nom_station) VALUES ('Les Hangars');
INSERT INTO Station(nom_station) VALUES ('Bassins � Flots');
INSERT INTO Station(nom_station) VALUES ('Rue Achard');
INSERT INTO Station(nom_station) VALUES ('New York');
INSERT INTO Station(nom_station) VALUES ('Brandenburg');
INSERT INTO Station(nom_station) VALUES ('Bordeaux Claveau');
INSERT INTO Station(nom_station) VALUES ('Begles Terres Neuves');
INSERT INTO Station(nom_station) VALUES ('Carle Vernet');
INSERT INTO Station(nom_station) VALUES ('Belcier');
INSERT INTO Station(nom_station) VALUES ('Gare Saint-Jean');
INSERT INTO Station(nom_station) VALUES ('Tauzia');
INSERT INTO Station(nom_station) VALUES ('Sainte-Croix');
INSERT INTO Station(nom_station) VALUES ('Saint-Michel');
INSERT INTO Station(nom_station) VALUES ('Place de la Bourse');
INSERT INTO Station(nom_station) VALUES ('Jardin Public');
INSERT INTO Station(nom_station) VALUES ('Place Paul Doumer');
INSERT INTO Station(nom_station) VALUES ('Camille Godard');
INSERT INTO Station(nom_station) VALUES ('Emile Counord');
INSERT INTO Station(nom_station) VALUES ('Grand Parc');
INSERT INTO Station(nom_station) VALUES ('Place Ravezies');
INSERT INTO Station(nom_station) VALUES ('Les Aubiers');
